#!/bin/bash
set -e
shopt -s extglob globstar checkwinsize

	cd "${1:-/ai/scripts}"
	declare -- start_dir="$PWD"
	cd -
	declare -- ext="${2:-}"
	declare -- hashbang="${3:-}"
	declare -- grep_string="${4:-}"
	declare -i files_only=1
	declare -a excludes=( 'python3.10'  ) Files=()
	declare -i edit_file=1 ccc=0
	declare -- grep
	grep=$(command -v grep)
		
	declare -p PWD ext hashbang files_only excludes grep_string
	
	while read -r file; do
		for ex in "${excludes[@]}"; do
			[[ "$file" == *"$ex"* ]] && continue 2
		done
		
		if ((files_only)); then
			#shellcheck disable=SC2015
			[[ -f "$file" ]] && [[ -r "$file" ]] || continue

			if [[ -n "$hashbang" ]]; then
				hdr=$(head -n1 "$file" 2>/dev/null | tr '\0' 'X' || echo '') || continue
				[[ "${hdr:0:2}" == '#!' || "${hdr:0:2}" == '<?' ]] || continue
				[[ "$hdr" == *"$hashbang"* ]] || continue
			fi
		
			if [[ -n "$grep_string" ]]; then
				"$grep" -qs "$grep_string" "$file" || continue
			fi
		fi
		((edit_file)) && {
			echo >&2 -n "$((++ccc))) "
			Files+=("$file")
		}
		echo "$file"
	done < <(locate "$start_dir"'/*'"$ext")

	((!edit_file)) && exit 0
	
	declare -i sel=0
	ccc=0
	while((1)); do
		echo
		read -rp "Select file to edit 0|1-${#Files[@]} " sel
		[[ -z "$sel" || $sel == '0' || $sel == 'q' ]] && exit 0
		$EDITOR "${Files[$sel]}"
		for file in "${Files[@]}"; do
			echo "$((++ccc))) $file"
		done
	done
	